export const ani = {
  Alert: "Anim_Chibi@Alert",
  Angry: "Anim_Chibi@Angry",
  Block: "Anim_Chibi@Block",
  Bow: "Anim_Chibi@Bow",
  Cute1: "Anim_Chibi@Cute1",
  Damage: "Anim_Chibi@Damage",
  Dash: "Anim_Chibi@Dash",
  DigA: "Anim_Chibi@DigA",
  DigB: "Anim_Chibi@DigB",
  Hi: "Anim_Chibi@Hi",
  Idle02: "Anim_Chibi@Idle02",
  Idle03: "Anim_Chibi@Idle03",
  Idle05: "Anim_Chibi@Idle05",
  IdleA: "Anim_Chibi@IdleA",
  IdleB: "Anim_Chibi@IdleB",
  IdleC: "Anim_Chibi@IdleC",
  Jump: "Anim_Chibi@Jump",
  Make_A: "Anim_Chibi@Make_A",
  Make_B: "Anim_Chibi@Make_B",
  Move: "Anim_Chibi@Move",
  Move_L: "Anim_Chibi@Move_L",
  Move_R: "Anim_Chibi@Move_R",
  No: "Anim_Chibi@No",
  NormalATK: "Anim_Chibi@NormalATK",
  Quadruped_Chiling: "Anim_Chibi@Quadruped_Chiling",
  Quadruped_Eating: "Anim_Chibi@Quadruped_Eating",
  Quadruped_Idle: "Anim_Chibi@Quadruped_Idle",
  Quadruped_Run: "Anim_Chibi@Quadruped_Run",
  Quadruped_Walk: "Anim_Chibi@Quadruped_Walk",
  Run: "Anim_Chibi@Run",
  Run_L: "Anim_Chibi@Run_L",
  Run_R: "Anim_Chibi@Run_R",
  Shoot: "Anim_Chibi@Shoot",
  Sit: "Anim_Chibi@Sit",
  Sleep: "Anim_Chibi@Sleep",
  Swiming: "Anim_Chibi@Swiming",
  Swoon: "Anim_Chibi@Swoon",
  Tired: "Anim_Chibi@Tired",
  Victory: "Anim_Chibi@Victory",
  Walk: "Anim_Chibi@Walk",
  Walk_L: "Anim_Chibi@Walk_L",
  Walk_R: "Anim_Chibi@Walk_R",
  Worship: "Anim_Chibi@Worship",
  Yes: "Anim_Chibi@Yes",
};

export const cameraPos = [
  {
    default: [],
    chat: [],
  },
  {
    default: [-1.34, 0.95, 1.2],
    chat: [-0.031, 0.404, 1.640],
  },
  {
    default: [1.139, 1.060, 0.974],
    chat: [0.145, 0.383, 1.438],
  },
];
